from typing import Protocol

from app.infrastructure.models import DealerModel, OrderModel, ProductModel


class DealerRepository(Protocol):
    async def get_by_email(self, email: str) -> DealerModel | None: ...
    async def get_by_id(self, dealer_id: int) -> DealerModel | None: ...
    async def add(self, dealer: DealerModel) -> DealerModel: ...


class ProductRepository(Protocol):
    async def list(self, search: str | None, category: str | None, page: int, size: int) -> tuple[list[ProductModel], int]: ...


class OrderRepository(Protocol):
    async def list_for_dealer(self, dealer_id: int) -> list[OrderModel]: ...
    async def add(self, order: OrderModel) -> OrderModel: ...
